[variables]
NIXPACKS_PHP_ROOT_DIR = "/app/public"
NIXPACKS_NODE_VERSION = "22"
DB_CONNECTION = "sqlite"
DB_DATABASE = "/app/database/database.sqlite"

[phases.install]
cmds = [
    "mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx",
    "composer install --ignore-platform-reqs",
    "npm install"
]

[phases.build]
cmds = [
    "npm run build",
    "touch database/database.sqlite",
    "chmod -R 777 database",
    "php artisan migrate --force --seed",
    "chmod 777 database/database.sqlite",
    "php artisan storage:link",
    "chmod -R 777 storage bootstrap/cache",
    "chown -R nixpacks:nixpacks database storage bootstrap/cache"
]
